spring.application.name=API_Gateway
# ===============================
# Eureka Configuration
# ===============================

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
server.port=8080
